;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; Place your private configuration here! Remember, you do not need to run 'doom
;; sync' after modifying this file!


;; Some functionality uses this to identify you, e.g. GPG configuration, email
;; clients, file templates and snippets. It is optional.
;; (setq user-full-name "John Doe"
;;       user-mail-address "john@doe.com")

;; Doom exposes five (optional) variables for controlling fonts in Doom:
;;
;; - `doom-font' -- the primary font to use
;; - `doom-variable-pitch-font' -- a non-monospace font (where applicable)
;; - `doom-big-font' -- used for `doom-big-font-mode'; use this for
;;   presentations or streaming.
;; - `doom-symbol-font' -- for symbols
;; - `doom-serif-font' -- for the `fixed-pitch-serif' face
;;
;; See 'C-h v doom-font' for documentation and more examples of what they
;; accept. For example:
;;
;;(setq doom-font (font-spec :family "Fira Code" :size 12 :weight 'semi-light)
;;      doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))
;;
;; If you or Emacs can't find your font, use 'M-x describe-font' to look them
;; up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
;; refresh your font settings. If Emacs still can't find your font, it likely
;; wasn't installed correctly. Font issues are rarely Doom issues!

;; There are two ways to load a theme. Both assume the theme is installed and
;; available. You can either set `doom-theme' or manually load a theme with the
;; `load-theme' function. This is the default:
(setq doom-theme 'doom-one)

;; This determines the style of line numbers in effect. If set to `nil', line
;; numbers are disabled. For relative line numbers, set this to `relative'.
(setq display-line-numbers-type t)

;; If you use `org' and don't want your org files in the default location below,
;; change `org-directory'. It must be set before org loads!
(setq org-directory "~/org/")


;; Whenever you reconfigure a package, make sure to wrap your config in an
;; `with-eval-after-load' block, otherwise Doom's defaults may override your
;; settings. E.g.
;;
;;   (with-eval-after-load 'PACKAGE
;;     (setq x y))
;;
;; The exceptions to this rule:
;;
;;   - Setting file/directory variables (like `org-directory')
;;   - Setting variables which explicitly tell you to set them before their
;;     package is loaded (see 'C-h v VARIABLE' to look them up).
;;   - Setting doom variables (which start with 'doom-' or '+').
;;
;; Here are some additional functions/macros that will help you configure Doom.
;;
;; - `load!' for loading external *.el files relative to this one
;; - `add-load-path!' for adding directories to the `load-path', relative to
;;   this file. Emacs searches the `load-path' when you load packages with
;;   `require' or `use-package'.
;; - `map!' for binding new keys
;;
;; To get information about any of these functions/macros, move the cursor over
;; the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
;; This will open documentation for it, including demos of how they are used.
;; Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
;; etc).
;;
;; You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
;; they are implemented.


;; Daoud's config generated by Gemini:

;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

;; ==========================================
;; 1. WINDOW AND GUI APPEARANCE
;; ==========================================

;; Set the window size on startup (Width x Height)
(add-to-list 'default-frame-alist '(width . 140))
(add-to-list 'default-frame-alist '(height . 45))

;; Clean UI: Remove the "old software" look
(setq display-line-numbers-type 'relative) ; Great for vim-style jumping
(remove-hook 'doom-first-input-hook #'global-hl-line-mode) ; Optional: turn off line highlight for cleaner look

;; Font handling - GUI looks best with specific weights
;; If these aren't installed, it will fallback to system mono
(setq doom-font (font-spec :family "Ubuntu Mono" :size 40 :weight 'light)
      doom-variable-pitch-font (font-spec :family "Ubuntu" :size 14))

;; Use a theme that looks great in GUI (similar to VS Code/PyCharm)
(setq doom-theme 'doom-one)

;; ==========================================
;; 2. THE "CONTROL-Z" REPLACEMENT (TERMINAL)
;; ==========================================

;; Map F4 to toggle a terminal at the bottom instead of minimizing.
;; (binding defined later via daoud/toggle-general-vterm)

;; Ensure vterm (the terminal) looks like your Ubuntu terminal
(setq vterm-shell "/bin/bash")

;; ==========================================
;; 3. PYTHON IDE FEATURES (LSP)
;; ==========================================

(after! python
  (setq python-shell-interpreter "python3")
  ;; Use "Pyright" for PyCharm-grade type checking
  (setq lsp-pyright-multi-root nil)
  
  ;; Enable "Breadcrumbs" at the top of the buffer (shows Class > Function)
  (setq lsp-headerline-breadcrumb-enable t)
  
  ;; Format on save using 'Black'
  (setq-hook! 'python-mode-hook +format-with-lsp nil) ; set to t if you want auto-format
)

;; ==========================================
;; 4. AI AGENTS (Claude / Gemini / GPT-4)
;; ==========================================

;; NOTE: You'll need (package! gptel) in your packages.el
(use-package! gptel
 :config
 (setq gptel-model 'claude-3-5-sonnet-20240620) ; Default for 2026
 ;; This allows you to select code and hit 'M-x gptel-send' to refactor
 (setq gptel-backend (gptel-make-anthropic "Claude" :key "YOUR_API_KEY_HERE")))

;; ==========================================
;; 5. MODERN GUI POLISH
;; ==========================================

;; Smooth pixel scrolling (GUI only)
(setq pixel-scroll-precision-mode t)

;; Show documentation tooltips instantly (like PyCharm)
(setq lsp-ui-doc-enable t
      lsp-ui-doc-delay 0.5
      lsp-ui-doc-position 'at-point)

;; ==========================================
;; 6. THE "DIRENV" MAGIC
;; ==========================================
;; This automatically loads your Python VirtualEnv when you open a file
;; based on the .envrc file in your project folder.
(use-package! envrc
  :config
  (envrc-global-mode))

;; Disable the exit confirmation prompt
(setq confirm-kill-emacs nil)


;; 1. The absolute essentials
(setq lsp-pyright-langserver-command "basedpyright")

;; 2. Make sure Emacs can find your pipx install
(add-to-list 'exec-path "/home/daoud/.local/bin")

;; 3. THE FIX: Reset the enablement lists
(after! lsp-mode
  (setq lsp-disabled-clients '(ty-ls)) ; Only block the one we hate
  (setq lsp-enabled-clients nil))      ; Setting to nil tells LSP to "detect anything allowed"


(after! lsp-ui
  (setq lsp-ui-doc-enable t
        lsp-ui-doc-show-with-cursor t    ; This is the key "PyCharm" behavior
        lsp-ui-doc-delay 0.5             ; 500ms delay so it's not flickering constantly
        lsp-ui-doc-position 'at-point    ; Keep it near the code
        lsp-ui-doc-include-signature t)) ; Show the function signature at the top

(after! lsp-ui
  (setq lsp-ui-sideline-enable t
        lsp-ui-sideline-show-diagnostics t
        lsp-ui-sideline-show-hover nil   ; We use the doc-popup for hovers instead
        lsp-ui-sideline-delay 0.2))


;; 1. Unbind the default minimize behavior
(global-unset-key (kbd "C-z"))
(global-unset-key (kbd "C-x C-z"))

(defun daoud/toggle-general-vterm ()
  "Toggle a dedicated general-purpose vterm, always separate from the Claude vterm."
  (interactive)
  (let* ((buf-name "*doom:vterm-general*")
         (buf (get-buffer buf-name))
         (win (and buf (get-buffer-window buf 'visible))))
    (cond
     ((and win (window-live-p win))
      (delete-window win))
     (buf
      (pop-to-buffer buf))
     (t
      (vterm buf-name)))))

;; 2. Map F4 to toggle the general terminal (works in all modes)
(map! :gniv "<f4>" #'daoud/toggle-general-vterm)

;; Force vterm popups to the right
(set-popup-rule! "^\\*doom:vterm" :side 'right :size 0.4 :select t :quit nil)

(defun daoud/toggle-claude-vterm ()
  "Toggle a dedicated Claude vterm.
   Creates it if missing, hides it if visible, shows it if hidden."
  (interactive)
  (let* ((buffer-name "*doom:vterm-claude*")
         (buffer (get-buffer buffer-name))
         (window (and buffer (get-buffer-window buffer 'visible))))
    (cond
     ;; Case 1: Window is visible -> Close the popup
     ((and window (window-live-p window))
      (delete-window window))

     ;; Case 2: Buffer exists but window is hidden -> Show it
     (buffer
      (pop-to-buffer buffer))

     ;; Case 3: No buffer exists -> Create, rename, and launch
     (t
      (+vterm/toggle nil)
      (let ((vterm-buffer (current-buffer)))
        (with-current-buffer vterm-buffer
          (rename-buffer buffer-name)
          (vterm-send-string "claude")
          (vterm-send-return)))))))

;; Bind it to F5
(map! "<f5>" #'daoud/toggle-claude-vterm)

;; Shortcut for recent files
(map! "<f2>" #'consult-recent-file)

(after! vterm
  ;; This tells vterm: "When I hit F5/C-z, don't send it to the shell; run my function."
  (define-key vterm-mode-map (kbd "<f5>") #'daoud/toggle-claude-vterm)
  (define-key vterm-mode-map (kbd "<f4>") #'daoud/toggle-general-vterm))

(after! vterm
  (define-key vterm-mode-map (kbd "<f2>") #'consult-recent-file))
